version: "3"
name: at-logistic
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:8.2-apache
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - mysql-network

  mysql:
    image: mysql:latest
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ats
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "9906:3306"
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql
      UPLOAD_LIMIT: 100000000
    networks:
      - mysql-network

networks:
  mysql-network:

volumes:
  mysql_data: